[build]
base = "."
command = "yarn build"
publish = "out"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/404"
status = 200

[build]
command = "npm run build"
environment = { NODE_VERSION = "18"}
functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["openai", "replicate", "node-fetch"]
  included_files = []

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-package-lock"

[dev]
  command = "npm run dev"
  targetPort = 8888
  publish = "public"
  framework = "#custom"
  autoLaunch = true

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200